version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - flashscore-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-test:
    container_name: postgres-test-db
    image: postgres:13.2-alpine
    ports:
      - $POSTGRES_TEST_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - flashscore-network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - postgres
    networks:
      - flashscore-network

  redis:
    container_name: redis
    image: redis
    ports:
      - $REDIS_PORT:6379
    networks:
      - flashscore-network

networks:
  flashscore-network:

volumes:
  pgdata:
